# vectordb.py


from pathlib import Path
from typing import Dict, List, Union

from local_vectors import LocalEmbedder, LanceDBConnection
import pyarrow as pa


class VectorDB:
	def __init__(self, 
		embed_model_id: str,
		db_path: str,
		token_overlap: int = 128,
		batch_size: int = 8,
		device: str = "cpu",
		use_binary: bool = False,
		model_save_root: str = Path.home() / ".cache" / "local-vectors" / "models",
	):
		# Initialize the local embedder and vector database connection.
		self.embedder = LocalEmbedder(
			embed_model_id,
			model_save_root=model_save_root,
			token_overlap=token_overlap,
			batch_size=batch_size,
			device=device,
		)
		self.db = LanceDBConnection(db_path)

		self.use_binary = use_binary
		self.required_fields = [
			"text_len", "text_idx", "vector", "subtext", "id"
		]

	
	# -- Utility functions centered around the embedder --
	def get_model_dims(self) -> int:
		return self.embedder.model_metadata["binary_dims"] if self.use_binary else self.embedder.model_metadata["dims"]
	

	def get_model_context_length(self) -> int:
		return self.embedder.model_metadata["context_length"]


	def set_device(self, device: str) -> None:
		self.embedder.set_device(device)

	
	def set_batch_size(self, batch_size: int) -> None:
		self.embedder.set_batch_size(batch_size)


	# -- Utility functions centered around the vector database --
	def validate_schema(self, schema: pa.Schema) -> None:
		if not all(field in schema.names for field in self.required_fields):
			raise AttributeError(f"Expected the following required fields to exist within the schema: {', '.join(self.required_fields)}. Found {', '.join(schema.names)}")


	def create_table(self, table_name: str, schema: pa.Schema) -> None:
		self.validate_schema(schema)
		self.db.create_table(table_name, schema=schema)


	def open_table(self, table_name: str) -> None:
		self.db.open_table(table_name)


	def update_table(self, table_name: str, data: List[dict], mode: str = "append") -> None:
		self.db.update_table(table_name, data, mode=mode)


	def delete_table(self, table_name: str) -> None:
		self.db.delete_table(table_name)


	def delete_all_tables(self) -> None:
		self.db.delete_all_tables()


	def search_table(self, 
		table_name: str, 
		query_vector: List[Union[float, int]], 
		top_k: int = 5, 
		metric: str = "cosine"
	) -> List[Dict]:
		return self.db.search_table(
			table_name, query_vector, top_k=top_k, metric=metric
		)


	# -- Document management and querying --
	def add_document(self, 
		doc_id: str, 
		text: str, 
		table_name: str, 
		mode: str = "append",
	) -> None:
		# Embed the document text.
		embeddings = self.embedder.embed_text(text, to_binary=self.use_binary)

		# Clean the embedding data.
		cleaned_embeddings = []
		for emb in embeddings:
			# Use a standard "vector" name for the vector field and add 
			# the appropriate embedding based on the use_binary setting.
			emb["vector"] = emb["vector_binary"] if self.use_binary else emb["vector_full"]

			# Remove the previous "vector" fields generated by 
			# self.embedder.embed_text.
			old_vector_names = ["vector_binary", "vector_full"]
			for name in old_vector_names:
				if name in emb:
					del emb[name]

			# Add the document ID to the embedding data for later 
			# reference.
			emb["id"] = doc_id
			cleaned_embeddings.append(emb)

		# Add the cleaned embedding data to the specified table in the 
		# vector database.
		self.update_table(table_name, cleaned_embeddings, mode=mode)


	def query(self, 
		text: str, 
		table_name: str, 
		top_k: int = 5, 
		metric: str = "cosine",
	) -> None:
		query_embedding = self.embedder.embed_text(
			text, 
			truncate=True,
			to_binary=self.use_binary
		)
		return self.search_table(
			table_name, 
			query_embedding, 
			top_k=top_k, 
			metric=metric
		)